
package Interfaz;

import EDD.Arbol;
import EDD.Nodo;
import Hashtable.ListaEnlazada;
import Hashtable.TablaHash;
import javax.swing.JOptionPane;

//import Hashtable.Hashtable;

/**
 *
 * @author jmmor
 */
public class buscarEspecie extends javax.swing.JFrame {
    static Arbol arbol;
//    Hashtable hash = new Hashtable();

    /**
     * Creates new form buscarEspecie
     */
    public buscarEspecie(Arbol a) {
        initComponents();
        this.arbol = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buscar = new javax.swing.JLabel();
        buscaPlanta = new javax.swing.JTextField();
        buscaHash = new javax.swing.JButton();
        buscaArbol = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        t = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        bontonVolverEnBuscarEspecie = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscar.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        buscar.setText("Buscar:");
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        buscaPlanta.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        buscaPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaPlantaActionPerformed(evt);
            }
        });
        jPanel1.add(buscaPlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 140, -1));

        buscaHash.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        buscaHash.setText("Busqueda por Hash Table");
        buscaHash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscaHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaHashActionPerformed(evt);
            }
        });
        jPanel1.add(buscaHash, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        buscaArbol.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        buscaArbol.setText("Busca por Arbol");
        buscaArbol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscaArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaArbolActionPerformed(evt);
            }
        });
        jPanel1.add(buscaArbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 180, -1));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        jLabel1.setText("Tiempo de busqueda: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        t.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        t.setText("0s");
        jPanel1.add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 490, 280));

        bontonVolverEnBuscarEspecie.setText("Volver al inicio");
        bontonVolverEnBuscarEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bontonVolverEnBuscarEspecieActionPerformed(evt);
            }
        });
        jPanel1.add(bontonVolverEnBuscarEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, -1, -1));

        jLabel2.setText("Si deseas ver graficamente el arbol de recorrido que se realizo para llegar a");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 450, -1));

        jLabel3.setText(" la especie  debe volver al inicio y presionar el botón de mostrar arbol.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscaPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaPlantaActionPerformed

    }//GEN-LAST:event_buscaPlantaActionPerformed

    private void buscaHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaHashActionPerformed
       JOptionPane.showMessageDialog(null, "Lamentablemente aun seguimos trabajando en esta parte. Sugerimos recorrer por arbol :D ");
     
    }//GEN-LAST:event_buscaHashActionPerformed

    
    /**
     * Este método realiza los siguientes pasos: - Obtiene el nombre de la
     * especie a buscar desde el campo de texto asociado. - Calcula el tiempo
     * empleado para realizar la búsqueda utilizando nanosegundos. - Utiliza el
     * método `busqueda` de la clase `Json` para obtener las características
     * asociadas a la especie buscada. - Muestra el tiempo de búsqueda en un
     * área de texto. - Itera sobre la lista de características obtenida y las
     * muestra en un área de texto.
     *
     * @param evt el evento de acción asociado al botón.
     */
    private void buscaArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaArbolActionPerformed
       
        String especieABuscar = this.buscaPlanta.getText();
    this.t.setText(" ");
try{
    long startTime = System.nanoTime();

    ListaEnlazada preguntas = Json.busqueda(especieABuscar);

    long endTime = System.nanoTime();
    long elapsedTime = (endTime - startTime);
    this.t.setText( elapsedTime + " Nanosegundos\n");
    
    // Mostrar los resultados de la búsqueda
    Nodo auxiliarLista = preguntas.getpFirst();
    while (auxiliarLista != null) {
        String dataComoTexto = String.valueOf(auxiliarLista.getData());
        this.jTextArea1.setText(this.jTextArea1.getText() + dataComoTexto + ", ");
        auxiliarLista = auxiliarLista.getpNext();
    }
} catch (Exception e) {
        JOptionPane.showMessageDialog(
            null,
            "No se ha cargado una clave dicotómica. Por favor, cárgala antes de buscar. 😊",
            "Advertencia",
            JOptionPane.WARNING_MESSAGE
        );
    }

    }//GEN-LAST:event_buscaArbolActionPerformed

    /**
     * Este método abre la ventana principal, establece su posición en el centro
     * de la pantalla y cierra la ventana actual.
     *
     * @param evt el evento de acción asociado al botón.
     */
    private void bontonVolverEnBuscarEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bontonVolverEnBuscarEspecieActionPerformed
       Arbolito arbolito= new Arbolito();
      arbolito.setVisible(true);
      arbolito.setLocationRelativeTo(null);
      this.dispose();
    }//GEN-LAST:event_bontonVolverEnBuscarEspecieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buscarEspecie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buscarEspecie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buscarEspecie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buscarEspecie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buscarEspecie(arbol).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bontonVolverEnBuscarEspecie;
    private javax.swing.JButton buscaArbol;
    private javax.swing.JButton buscaHash;
    private javax.swing.JTextField buscaPlanta;
    private javax.swing.JLabel buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel t;
    // End of variables declaration//GEN-END:variables
}
