/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import EDD.Arbol;
import EDD.Nodo;
//import Hashtable.Hashtable;

/**
 *
 * @author jmmor
 */
public class buscarEspecie extends javax.swing.JFrame {
    static Arbol arbol;
//    Hashtable hash = new Hashtable();

    /**
     * Creates new form buscarEspecie
     */
    public buscarEspecie(Arbol a) {
        initComponents();
        this.arbol = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buscar = new javax.swing.JLabel();
        buscaPlanta = new javax.swing.JTextField();
        buscaHash = new javax.swing.JButton();
        buscaArbol = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        t = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscar.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        buscar.setText("Buscar:");
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        buscaPlanta.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        buscaPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaPlantaActionPerformed(evt);
            }
        });
        jPanel1.add(buscaPlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 140, -1));

        buscaHash.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        buscaHash.setText("Busqueda por Hash Table");
        buscaHash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscaHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaHashActionPerformed(evt);
            }
        });
        jPanel1.add(buscaHash, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        buscaArbol.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        buscaArbol.setText("Busca por Arbol");
        buscaArbol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscaArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaArbolActionPerformed(evt);
            }
        });
        jPanel1.add(buscaArbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        jLabel1.setText("Tiempo de busqueda: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        t.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        t.setText("0s");
        jPanel1.add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscaPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaPlantaActionPerformed

    }//GEN-LAST:event_buscaPlantaActionPerformed

    private void buscaHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaHashActionPerformed
        // TODO add your handling code here:

        try {

            long startTime = System.nanoTime();
//            String nombre = this.buscaPlanta.getText();
//            Nodo n = hash.buscar(nombre);
//            
//            
//            
//            
            long estimatedTime = System.nanoTime() - startTime;
            t.setText(estimatedTime + "s");
        } catch (Exception e) {

        }
    }//GEN-LAST:event_buscaHashActionPerformed

    private void buscaArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaArbolActionPerformed
        // TODO add your handling code here:
        
        try {

            long startTime = System.nanoTime();
            String nombre = this.buscaPlanta.getText();
            String resultado = this.arbol.posordenSearch(nombre);
            this.jTextArea1.setText(resultado);
//            Nodo n = hash.buscar(nombre);
//            
//            
//            
//            
            long estimatedTime = System.nanoTime() - startTime;
            t.setText(estimatedTime + "s");
        } catch (Exception e) {

        }
    }//GEN-LAST:event_buscaArbolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buscarEspecie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buscarEspecie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buscarEspecie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buscarEspecie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buscarEspecie(arbol).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscaArbol;
    private javax.swing.JButton buscaHash;
    private javax.swing.JTextField buscaPlanta;
    private javax.swing.JLabel buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel t;
    // End of variables declaration//GEN-END:variables
}
